### ISSUE TITLE
ArgumentError: Option name hard_wrap is already used

### ISSUE THREAD

**Issue by ashmaroli** [kramdown/parser-gfm#3]
Running `rake` tasks get aborted with the following:
```
$ rake
rake aborted!
ArgumentError: Option name hard_wrap is already used
~/parser-gfm/lib/kramdown/parser/gfm.rb:16:in `<module:Options>'
~/parser-gfm/lib/kramdown/parser/gfm.rb:14:in `<module:Kramdown>'
~/parser-gfm/lib/kramdown/parser/gfm.rb:13:in `<top (required)>'
~/parser-gfm/Rakefile:7:in `require_relative'
~/parser-gfm/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by gettalong** [comment]
That is expected since these repos depend on kramdown 2.0.

**Comment by ashmaroli** [comment]
Sucks to have the rake tasks crippled till kramdown-2.0 ships.. :disappointed:

**Comment by gettalong** [comment]
Maybe, but this repo/gem is only useful once 2.0 is released.

**Comment by gettalong** [comment]
If you use the pre-release version of kramdown, it should work now!
